### ISSUE TITLE
Histogram counts can overflow

### ISSUE THREAD

**Issue by speezepearson** [ArpNetworking/metrics-aggregator-daemon#171]
IIUC, a `HistogramStatistic`s stores its bin-counts in ([essentially](http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/doubles/Double2IntAVLTreeMap.html)) a `Map<double, int>`. And `int` maxes out at 2^31.

Consider:
- 10M hosts
- ...each logging to a metric 5/sec
- ...for 1 minute
- ...is 3B samples
- ...which overflows to a count of -1294967296.

"10M hosts" and "5/sec" sound perfectly plausible in our medium-term future.

**Comment by vjkoskela** [comment]
Histogram bucket counts are now longs.
