### ISSUE TITLE
Missed Cases of Thread Local Builder Usage

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/metrics-aggregator-daemon#80]
There are still usages of the following thread local builders which do not utilize the thread local build path.

* PeriodicData.Builder
* DefaultRecord.Builder

This is as of version `1.9.1`.

**Comment by vjkoskela** [comment]
I'm seeing about 1600 per minute under light load (e.g. almost jvm and system samples only).

**Comment by BrandonArp** [comment]
Partially addressed by #81   Waiting to see others before closing the issue.

**Comment by vjkoskela** [comment]
I'm now only seeing ones from instantiating parsers on config load. Sources are not built with ThreadLocal but for some reason the parsers are. This will be addressed (at least for the common case) with canonical sources (e.g. with hard-coded parser bindings). Also, I don't think that either sources or parsers are built frequently enough that this is a problem. Resolving. Reopen if more occurrences are found.
